
{
  LinearLayout;
  orientation="vertical";
  layout_width="fill";
  layout_height="fill";
  {
    LinearLayout;
    background=draw.weak;
    elevation="2dp";
    layout_width="fill";
    id="status_bar";
  };
  {
    LinearLayout;
    orientation="horizontal";
    layout_width="fill";
    background=draw.weak;
    layout_height="54dp";
    elevation="3dp";

    {
      LinearLayout;
      orientation="horizontal";
      layout_height="fill";
      layout_weight="1";
      {
        TextView;
        layout_marginLeft="14dp";
        text="设置";
        id="title";
        textSize="22sp";
        layout_gravity="center";
        textColor=draw.back;
        layout_margin="6dp";
      };
      {
        LinearLayout;
        gravity="end";
        layout_gravity="end";
        layout_height="fill";
        layout_width="fill";
        {
          LinearLayout;
          layout_height="fill";
          layout_gravity="center";
          layout_width="24%w";
          layout_margin="10dp";
        };
        {
          LinearLayout;
          gravity="center";
          layout_height="fill";
          layout_width="16%w";
          id="sett";
          {
            ImageView;
            layout_width="0";
            src="res/drawable/set.png";
            colorFilter=draw.bright;
            layout_height="25dp";
          };
        };
        {
          LinearLayout;
          gravity="center";
          layout_height="fill";
          layout_width="12%w";
          id="exit";
          gravity="center";
          {
            ImageView;
            layout_width="25dp";
            src="res/drawable/exit.png";
            colorFilter=draw.bright;
            layout_height="25dp";
            -- layout_margin="5dp";
          };
        };
      };
    };
  };
  {
    FrameLayout;
    layout_width="fill";
    layout_height="fill";

    {
      LinearLayout;
      orientation="vertical";
      layout_width="fill";
      background=draw.back;
      layout_height="fill";
      gravity="center";
      id="mainlays";
      {
        LinearLayout;
        layout_height="fill";
        id="mainlay";
        layout_width="fill";
        orientation="vertical";
        {
          ScrollView;
          verticalScrollBarEnabled=false;
          layout_width="fill";
          layout_height="fill";
          {
            LinearLayout;
            layout_height="fill";
            id="scroll";
            layout_width="fill";
            orientation="vertical";
            {
              CardView;
              layout_marginTop="2%h";
              layout_margin="7dp";
              layout_height="wrap";
              CardBackgroundColor=draw.pureday;
              id="introcard";
              radius="2dp";
              layout_width="fill";
              elevation="2dp";
              {
                LinearLayout;
                orientation="vertical";
                layout_width="fill";
                layout_height="fill";
                {
                  ImageView;
                  id="intropic";
                  scaleType="centerInside";
                  layout_margin="5dp";
                  layout_height="40%w";
                  layout_width="fill";
                  src="res/drawable/code.png";
                };
                {
                  LinearLayout;
                  gravity="right";
                  layout_width="fill";
                  layout_height="wrap";
                  orientation="vertical";
                  {
                    TextView;
                    gravity="end";
                    layout_margin="6dp";
                    layout_height="wrap";
                    layout_gravity="right";
                    text=[==[  不知道  ]==];
                    textColor=draw.ink;
                    layout_width="80%w";
                    textSize="12sp";
                  };
                  {
                    ProgressBar,
                    layout_marginTop="-2dp",
                    visibility=0,
                    indeterminate=true,
                    style="?android:attr/progressBarStyleHorizontal",
                    layout_width="fill",
                    layout_height="8dp",
                    layout_gravity="center";
                    id="loadbar";
                  };
                };
              };
            };
            {
              CardView;
              layout_margin="7dp";
              layout_height="wrap";
              layout_marginTop="10dp";
              CardBackgroundColor=draw.bright;
              radius="2dp";
              layout_width="fill";
              elevation="2dp";
              {
                LinearLayout;
                backgroundColor=draw.bright;
                layout_height="wrap";
                layout_width="fill";
                orientation="vertical";
                {
                  TextView;
                  layout_marginLeft="10dp";
                  id="Developer_title";
                  layout_height="45dp";
                  gravity="left|center";
                  textSize="15sp";
                  textColor=draw.weak;
                  layout_width="fill";
                  text="开发人员";
                };
                {
                  LinearLayout;
                  layout_height="wrap";
                  layout_width="fill";
                  orientation="horizontal";
                  {
                    LinearLayout;
                    backgroundColor=draw.pureday;
                    layout_height="wrap";
                    layout_width="fill";
                    orientation="vertical";
                    {
                      LinearLayout;
                      id="d1";
                      layout_height="wrap";
                      backgroundColor="#ffffffff";
                      layout_width="fill";
                      orientation="horizontal";
                      {
                        CircleImageView;
                        layout_margin="10dp";
                        layout_height="40dp";
                        layout_gravity="center";
                        layout_width="40dp";
                        id="d1pic";
                      };
                      {
                        LinearLayout;
                        orientation="vertical";
                        layout_width="fill";
                        layout_height="wrap";
                        layout_gravity="center";
                        {
                          TextView;
                          text="45iron";
                          textColor="#F5141414";
                          id="d1name";
                          textSize="16";
                        };
                        {
                          TextView;
                          text="45钢，强中强";
                          id="d1intro";
                        };
                      };
                    };
                  };
                };
              };
            };
            {
              CardView;
              layout_margin="7dp";
              layout_height="wrap";
              layout_marginTop="10dp";
              CardBackgroundColor=draw.back;
              radius="2dp";
              layout_width="fill";
              elevation="3dp";
              {
                LinearLayout;
                backgroundColor=draw.bright;
                layout_height="wrap";
                layout_width="fill";
                orientation="vertical";
                {
                  TextView;
                  layout_marginLeft="10dp";
                  id="set_title";
                  layout_height="45dp";
                  gravity="left|center";
                  textSize="15sp";
                  textColor=draw.weak;
                  layout_width="fill";
                  text="设置";
                };
                {
                  LinearLayout;
                  layout_width="fill";
                  orientation="vertical";
                  layout_height="60dp";
                  backgroundColor=draw.pureday;
                  {
                    LinearLayout;
                    {
                      TextView;
                      textSize="15sp";
                      layout_marginTop="0dp";
                      layout_height="60dp";
                      layout_marginLeft="6%w";
                      text="启用缓存机制";
                      textColor="#FF222222";
                      layout_width="74%w";
                      gravity="left|center";
                    };
                    {
                      Switch;
                      layout_marginTop="0dp";
                      id="issave";
                    };
                  };
                };
                {
                  LinearLayout;
                  layout_width="fill";
                  orientation="vertical";
                  layout_height="60dp";
                  backgroundColor=draw.pureday;
                  {
                    LinearLayout;
                    {
                      TextView;
                      textSize="15sp";
                      layout_marginTop="0dp";
                      layout_height="60dp";
                      layout_marginLeft="6%w";
                      text="启用模糊显示";
                      textColor="#FF222222";
                      layout_width="74%w";
                      gravity="left|center";
                    };
                    {
                      Switch;
                      layout_marginTop="0dp";
                      id="ispubu";
                    };
                  };
                };
             
             
                {
                  LinearLayout;
                  orientation="vertical";
                  layout_width="fill";
                  layout_height="wrap";
                  backgroundColor=draw.pureday;
                  {
                    TextView;
                    id="saveout";
                    gravity="left|center";
                    textSize="15sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    style="?android:attr/buttonBarButtonStyle";
                    text="更改目标贴吧";
                    layout_marginLeft="2%w";
                    layout_height="wrap";
                  };
                  {
                    TextView;
                    id="路径喵";
                    gravity="left|center";
                    textSize="10sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    layout_marginTop="0dp";
                    text="The path is here";
                    layout_marginLeft="2%w";
                    layout_height="0";
                  };
                };
              
                {
                  LinearLayout;
                  orientation="vertical";
                  layout_width="fill";
                  layout_height="wrap";
                  backgroundColor=draw.pureday;
                  {
                    TextView;
                    id="impos";
                    gravity="left|center";
                    textSize="15sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    style="?android:attr/buttonBarButtonStyle";
                    text="修改首页页数";
                    layout_marginLeft="2%w";
                    layout_height="wrap";
                  };
                  {
                    TextView;
                    id="路径喵";
                    gravity="left|center";
                    textSize="10sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    layout_marginTop="0dp";
                    text="The path is here";
                    layout_marginLeft="2%w";
                    layout_height="0";
                  };
                };
              
                {
                  LinearLayout;
                  orientation="vertical";
                  layout_width="fill";
                  layout_height="wrap";
                  backgroundColor=draw.pureday;
                  {
                    TextView;
                    id="importins";
                    gravity="left|center";
                    textSize="15sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    style="?android:attr/buttonBarButtonStyle";
                    text="帖子分析";
                    layout_marginLeft="2%w";
                    layout_height="wrap";
                  };
                  {
                    TextView;
                    id="路径喵";
                    gravity="left|center";
                    textSize="10sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    layout_marginTop="0dp";
                    text="The path is here";
                    layout_marginLeft="2%w";
                    layout_height="0";
                  };
                };
                {
                  LinearLayout;
                  orientation="vertical";
                  layout_width="fill";
                  layout_height="wrap";
                  backgroundColor=draw.pureday;
                  {
                    TextView;
                    id="Webdavup";
                    gravity="left|center";
                    textSize="15sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    style="?android:attr/buttonBarButtonStyle";
                    text="帖子跟踪";
                    layout_marginLeft="2%w";
                    layout_height="wrap";
                  };
                  {
                    TextView;
                    id="路径喵";
                    gravity="left|center";
                    textSize="10sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    layout_marginTop="0dp";
                    text="The path is here";
                    layout_marginLeft="2%w";
                    layout_height="0";
                  };
                };
              };
            };
            {
              CardView;
              layout_margin="7dp";
              layout_height="wrap";
              layout_marginTop="10dp";
              CardBackgroundColor=draw.bright;
              radius="2dp";
              layout_width="fill";
              elevation="4dp";

              {
                LinearLayout;
                --backgroundColor=draw.back;
                layout_height="wrap";
                layout_width="fill";
                orientation="vertical";
                {
                  TextView;
                  layout_marginLeft="10dp";
                  id="other_title";
                  layout_height="45dp";
                  gravity="left|center";
                  textSize="15sp";
                  textColor=draw.weak;
                  layout_width="fill";
                  text="其他";
                };
                {
                  LinearLayout;
                  layout_height="wrap";
                  layout_width="fill";
                  orientation="horizontal";
                  backgroundColor=draw.pureday;
                  {
                    LinearLayout;
                    gravity="center";
                    layout_width="15%w";
                    layout_height="15%w";
                    {
                      ImageView;
                      layout_height="24dp";
                      layout_width="24dp";
                      src="res/drawable/twotone_wb_cloudy_black_24dp.png";
                    };
                  };
                  {
                    TextView;
                    layout_margin="1dp";
                    layout_height="fill";
                    textSize="16sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    style="?android:attr/buttonBarButtonStyle";
                    layout_marginTop="4dp";
                    text="开源使用";
                    gravity="top";
                    id="开源";
                  };
                };
                {
                  LinearLayout;
                  layout_height="wrap";
                  layout_width="fill";
                  orientation="horizontal";
                  backgroundColor=draw.pureday;
                  {
                    LinearLayout;
                    gravity="center";
                    layout_width="15%w";
                    layout_height="15%w";
                    {
                      ImageView;
                      layout_height="24dp";
                      layout_width="24dp";
                      src="res/drawable/twotone_equalizer_black_24dp.png";
                    };
                  };
                  {
                    TextView;
                    layout_margin="1dp";
                    layout_height="fill";
                    textSize="16sp";
                    textColor="#FF222222";
                    layout_width="fill";
                    style="?android:attr/buttonBarButtonStyle";
                    text="反馈问题";
                    gravity="top";
                    id="反馈";
                  };
                };
              };
            };
            {
              LinearLayout;
              layout_height="40dp";
              gravity="center";
              layout_width="fill";
              orientation="horizontal";
              {
                TextView;
                id="隐私";
                layout_gravity="center";
                text="隐私政策";
                layout_margin="10dp";
                textSize="14sp";
              };
              {
                TextView;
                id="协议";
                layout_gravity="center";
                text="用户协议";
                layout_margin="10dp";
                textSize="14sp";
              };

            };
          };
        };
      };
      
    };
  };
};
