
--repo
--至少blan，urls，name，intro，pict
subitems={
  {
    LinearLayout;
    layout_width="fill";
    {
      LinearLayout;
      layout_width="fill";
      orientation="vertical";
      gravity="center";
      layout_height="wrap";
      {
        CardView;
        layout_width="fill";
        layout_margin="8dp";
        elevation="3dp";
        radius="6dp";
        layout_height="22%w";
        CardBackgroundColor="#ffffffff";
        id="card";
        {
          LinearLayout;
          layout_width="fill";
          layout_margin="4dp";
          orientation="horizontal";
          layout_height="fill";
          {
            LinearLayout;
            layout_width="16%w";
            gravity="center";
            layout_height="fill";
            {
              CircleImageView;
              layout_width="40dp";
              layout_margin="10dp";
              layout_height="40dp";
              layout_gravity="center";
              id="pict";
            };
          };
          {
            LinearLayout;
            layout_width="fill";
            gravity="center";
            orientation="vertical";
            layout_height="fill";
            {
              LinearLayout;
              layout_width="fill";
              layout_height="11%w";
              {
                TextView;
                textSize="18sp";
                textColor="#FF222222";
                layout_height="fill";
                gravity="center";
                layout_margin="6dp";
                text="项目名称";
                id="name";
              };
            };
            {
              LinearLayout;
              layout_width="fill";
              layout_height="11%w";
              {
                TextView;
                layout_margin="6dp";
                text="本项目介绍";
                id="intro";
              };
              {
                TextView;
                layout_width="0";
                layout_height="0";
                id="urls";
              };
              {
                TextView;
                layout_width="0";
                layout_height="0";
                id="blan";
              };
            };
          }
        };
      };
    };
  };

  --**************/
  --repo02
  {
    LinearLayout;
    layout_width="fill";
    {
      LinearLayout;
      orientation="vertical";
      layout_height="wrap";
      gravity="center";
      layout_width="fill";
      {
        CardView;
        id="card";
        layout_height="22%w";
        radius="6dp";
        layout_width="fill";
        CardBackgroundColor="#ffffffff";
        elevation="3dp";
        layout_margin="8dp";
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="fill";
          layout_width="fill";
          layout_margin="0dp";
          {
            LinearLayout;
            layout_height="fill";
            gravity="center";
            layout_width="22%w";
            {
              ImageView;
              scaleType="centerCrop";
              layout_height="fill";
              --src="res/upload.png";
              id="pict";
              layout_width="fill";
            };
          };
          {
            LinearLayout;
            orientation="vertical";
            layout_height="fill";
            gravity="center";
            layout_width="fill";
            {
              LinearLayout;
              layout_width="fill";
              layout_height="11%w";
              {
                TextView;
                text="项目名称";
                layout_height="fill";
                textSize="18sp";
                textColor="#FF222222";
                id="name";
                gravity="center";
                layout_margin="6dp";
              };
            };
            {
              LinearLayout;
              orientation="horizontal";
              layout_height="11%w";
              layout_gravity="start";
              gravity="start";
              layout_width="fill";
              {
                LinearLayout;
                layout_height="fill";
                layout_width="60%w";
                {
                  TextView;
                  text="本项目介绍";
                  layout_gravity="left";
                  id="intro";
                  layout_margin="6dp";
                };
              };
              {
                LinearLayout;
                orientation="vertical";
                layout_height="fill";
                layout_gravity="end";
                gravity="bottom";
                layout_width="fill";
                {
                  ImageView;
                  layout_gravity="right";
                  layout_height="25dp";
                  src="res/drawable/02.png";
                  layout_width="25dp";
                  layout_margin="4dp";
                  colorFilter="#FF56B2DB";
                };
              };
              {
                TextView;
                id="urls";
                layout_height="0";
                layout_width="0";
              };
              {
                TextView;
                id="blan";
                layout_height="0";
                layout_width="0";
              };
            };
          };
        };
      };
    };
  };
  -------*********02
  {
    LinearLayout;
    layout_width="fill";
    {
      LinearLayout;
      layout_width="fill";
      layout_height="wrap";
      orientation="vertical";
      gravity="center";
      {
        CardView;
        layout_width="fill";
        id="card";
        radius="6dp";
        elevation="3dp";
        layout_height="wrap";
        CardBackgroundColor="#ffffffff";
        layout_margin="8dp";
        {
          LinearLayout;
          layout_width="fill";
          layout_height="fill";
          orientation="horizontal";
          layout_margin="4dp";
          {
            LinearLayout;
            layout_width="fill";
            layout_height="fill";
            orientation="vertical";
            gravity="center";
            {
              LinearLayout;
              layout_width="fill";
              layout_height="11%w";
              {
                TextView;
                textSize="18sp";
                text="项目名称";
                gravity="center";
                id="name";
                layout_height="fill";
                layout_margin="6dp";
                textColor="#FF222222";
              };
            };
            {
              LinearLayout;
              layout_width="fill";
              layout_height="wrap";
              {
                TextView;
                layout_margin="6dp";
                layout_width="fill";
                text=[==[无文本]==];
                id="intro";
              };
              {
                TextView;
                layout_width="0";
                layout_height="0";
                id="urls";
              };
              {
                TextView;
                layout_width="0";
                layout_height="0";
                id="blan";
              };
            };
            {
              LinearLayout;
              layout_width="fill";
              layout_height="8%w";
              orientation="horizontal";
              gravity="end";
              {
                ImageView;
                layout_margin="4dp";
                scaleType="centerInside";
                layout_gravity="right";
                layout_height="25dp";
                src="res/drawable/03.png";
                colorFilter="#FF56B2DB";
                layout_width="25dp";
              };
            };
          };
        };
      };
    };
  };
  -------4444
  {
    LinearLayout;
    layout_width="fill";
    {
      LinearLayout;
      orientation="vertical";
      layout_height="wrap";
      gravity="center";
      layout_width="fill";
      {
        CardView;
        id="card";
        layout_width="fill";
        elevation="3dp";
        CardBackgroundColor=draw.bright;
        layout_height="wrap";
        radius="3dp";
        layout_margin="10dp";
        {
          LinearLayout;
          layout_marginTop="5dp";
          layout_height="wrap";
          layout_width="fill";
          orientation="vertical";
          {
            LinearLayout;
            layout_width="fill";
            layout_height="3%h";
            {
              LinearLayout;
              gravity="center";
              orientation="horizontal";
              layout_width="wrap";
              {
                TextView;
                layout_marginLeft="8dp";
                id="name";
                textColor=draw.ink;
                textSize="14";
                singleLine="true";
                text="用户名啊啊";
              };
              {
                TextView;
                layout_gravity="end";
                id="date";
                text="2-18";
                textColor=draw.ink;
                layout_marginLeft="8dp";
              };
            };
            {
              LinearLayout;
              layout_width="fill";
              gravity="end";
              {
                TextView;
                id="comment";
                textColor=draw.ink;
                layout_marginRight="8dp";
                text="42";
                textSize="14";
              };
            };
          };
          {
            LinearLayout;
            layout_marginTop="5dp";
            layout_height="13%h";
            layout_width="fill";
            orientation="horizontal";
            {
              LinearLayout;
              id="imgf";
              layout_height="fill";
              layout_width="0";
              gravity="center";
              {
                ImageView;
                id="img";
                layout_height="15%h";
                layout_width="15%h";
                scaleType="fitXY";
              };
            };
            {
              LinearLayout;
              layout_width="fill";
              layout_height="fill";
              {
                TextView;
                textColor=draw.dead;
                textSize="16";
                id="content";
                text=[==[.
]==];
                layout_margin="8dp";
              };
            };
          };
        };
      };
    };
    {
      TextView;
      layout_height="0";
      layout_width="0";
      id="is_bakan";
    };
    {
      TextView;
      layout_height="0";
      layout_width="0";
      id="kz";
    };
    {
      TextView;
      layout_height="0";
      layout_width="0";
      id="lp";
    };
  };

  -----------5
  {
    LinearLayout;
    layout_height="wrap";
    layout_width="fill";
    {
      LinearLayout;
      layout_width="fill";
      gravity="center";
      orientation="vertical";
      layout_height="wrap";
      {
        CardView;
        elevation="2dp";
        layout_width="fill";
        radius="3dp";
        layout_height="wrap";
        layout_margin="10dp";
        id="card";
        CardBackgroundColor=draw.bright;
        {
          LinearLayout;
          layout_height="wrap";
          layout_width="fill";
          orientation="vertical";
          layout_marginTop="5dp";
          {
            LinearLayout;
            layout_height="3%h";
            layout_width="fill";
            {
              LinearLayout;
              gravity="center";
              orientation="horizontal";
              layout_width="wrap";
              {
                TextView;
                textSize="14";
                text="用户";
                id="name";
                textColor=draw.ink;
                layout_marginLeft="8dp";
                singleLine="true";
              };
              {
                TextView;
                layout_marginLeft="8dp";
                id="date";
                layout_gravity="end";
                textColor=draw.ink;
                text="时间";
              };
            };
            {
              LinearLayout;
              gravity="end";
              layout_width="fill";
              {
                TextView;
                textSize="14";
                layout_marginRight="8dp";
                id="floor";
                textColor=draw.ink;
                text="楼层";
              };
            };
          };
          {
            LinearLayout;
            layout_height="wrap";
            layout_width="fill";
            orientation="horizontal";
            layout_marginTop="5dp";
            {
              LinearLayout;
              gravity="center";
              layout_width="0";
              id="imgf";
              layout_height="fill";
              {
                ImageView;
                scaleType="fitXY";
                layout_width="15%h";
                id="img";
                layout_height="15%h";
              };
            };
            {
              LinearLayout;
              layout_width="fill";
              orientation="vertical";
              layout_height="wrap";
              {
                TextView;
                textSize="16";
                textColor="#FF323232";
                layout_margin="8dp";
                id="content";
                text=[==[
                            内容显示错误,或无内容
                            ]==];
              };
              {
                LinearLayout;
                layout_width="fill";
                -- orientation="vertical";
                layout_height="wrap";
                layout_gravity="center";
                layout_margin="8dp";
                {
                  GridView;
                  numColumns="6",--设置列数
                  overScrollMode="2",--去除滑动圆弧形
                  verticalScrollBarEnabled=false,--隐藏滑条
                  -- gravity="center";
                  layout_width="fill";
                  layout_height="wrap";
                  numColumns=9;
                  id='imglist';
                };
              };
            };
          };
        };
      };
    };
    {
      TextView;
      layout_width="0";
      id="is_bakan";
      layout_height="0";
    };
    {
      TextView;
      layout_width="0";
      id="kz";
      layout_height="0";
    };
    {
      TextView;
      layout_width="0";
      id="lp";
      layout_height="0";
    };
  };
}